-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 09:34:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema domicilios
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paises` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paises` (
  `codPais` INT NOT NULL AUTO_INCREMENT,
  `estatus` VARCHAR(100) NOT NULL,
  `nombrePais` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codPais`));


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `codEstado` INT NOT NULL AUTO_INCREMENT,
  `nombreEstado` VARCHAR(100) NOT NULL,
  `paises_codPais` INT NOT NULL,
  PRIMARY KEY (`codEstado`),
  CONSTRAINT `fk_estados_paises1`
    FOREIGN KEY (`paises_codPais`)
    REFERENCES `mydb`.`paises` (`codPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_estados_paises1_idx` ON `mydb`.`estados` (`paises_codPais` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`municipios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`municipios` (
  `nombreMunicipio` VARCHAR(100) NOT NULL,
  `codMunicipio` INT NOT NULL AUTO_INCREMENT,
  `estados_codEstado` INT NOT NULL,
  PRIMARY KEY (`codMunicipio`),
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_codEstado`)
    REFERENCES `mydb`.`estados` (`codEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_municipios_estados1_idx` ON `mydb`.`municipios` (`estados_codEstado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`parroquias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parroquias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parroquias` (
  `nombreParroquia` VARCHAR(100) NOT NULL,
  `codParroquia` INT NOT NULL AUTO_INCREMENT,
  `municipios_codMunicipio` INT NOT NULL,
  PRIMARY KEY (`codParroquia`),
  CONSTRAINT `fk_parroquias_municipios1`
    FOREIGN KEY (`municipios_codMunicipio`)
    REFERENCES `mydb`.`municipios` (`codMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_parroquias_municipios1_idx` ON `mydb`.`parroquias` (`municipios_codMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ciudades` (
  `codCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombreCiudad` VARCHAR(100) NOT NULL,
  `parroquias_codParroquia` INT NOT NULL,
  PRIMARY KEY (`codCiudad`),
  CONSTRAINT `fk_ciudades_parroquias1`
    FOREIGN KEY (`parroquias_codParroquia`)
    REFERENCES `mydb`.`parroquias` (`codParroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_ciudades_parroquias1_idx` ON `mydb`.`ciudades` (`parroquias_codParroquia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(30) NOT NULL,
  `apellidoPersona` VARCHAR(30) NOT NULL,
  `cedulaPersona` VARCHAR(30) UNIQUE NOT NULL,
  `sexoPersona` VARCHAR(30) NOT NULL,
  `codVivienda` INT NOT NULL,
  `fechaNac` VARCHAR(30) NOT NULL,
  `ciudades_codCiudad` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_personas_ciudades1`
    FOREIGN KEY (`ciudades_codCiudad`)
    REFERENCES `mydb`.`ciudades` (`codCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_personas_ciudades1_idx` ON `mydb`.`personas` (`ciudades_codCiudad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `telefonoPrincipal` VARCHAR(30) NOT NULL,
  `telefonoSecundario` VARCHAR(30) NOT NULL,
  `emailPrincipal` VARCHAR(30) NOT NULL,
  `emailSecundario` VARCHAR(30) NOT NULL,
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idContacto`));


-- -----------------------------------------------------
-- Table `mydb`.`maestros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`maestros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`maestros` (
  `estadoCivil` VARCHAR(30) NOT NULL,
  `cargoActual` VARCHAR(30) NOT NULL,
  `idMaestro` INT NOT NULL AUTO_INCREMENT,
  `personas_idPersona` INT NOT NULL,
  `contacto_idContacto` INT NOT NULL,
  PRIMARY KEY (`idMaestro`),
  CONSTRAINT `fk_maestros_personas1`
    FOREIGN KEY (`personas_idPersona`)
    REFERENCES `mydb`.`personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maestros_contacto1`
    FOREIGN KEY (`contacto_idContacto`)
    REFERENCES `mydb`.`contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_maestros_personas1_idx` ON `mydb`.`maestros` (`personas_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_maestros_contacto1_idx` ON `mydb`.`maestros` (`contacto_idContacto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`representantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`representantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`representantes` (
  `estadoCivil` VARCHAR(30) NOT NULL,
  `parentesco` VARCHAR(30) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `idRepresentante` INT NOT NULL AUTO_INCREMENT,
  `personas_idPersona` INT NOT NULL,
  `contacto_idContacto` INT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  CONSTRAINT `fk_representantes_personas1`
    FOREIGN KEY (`personas_idPersona`)
    REFERENCES `mydb`.`personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representantes_contacto1`
    FOREIGN KEY (`contacto_idContacto`)
    REFERENCES `mydb`.`contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_representantes_personas1_idx` ON `mydb`.`representantes` (`personas_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_representantes_contacto1_idx` ON `mydb`.`representantes` (`contacto_idContacto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudiantes` (
  `cedulaEstudiantil` INT NOT NULL,
  `alergias` VARCHAR(30) NOT NULL,
  `enfermedades` VARCHAR(30) NOT NULL,
  `estatura` VARCHAR(30) NOT NULL,
  `peso` VARCHAR(30) NOT NULL,
  `tallaCalzado` VARCHAR(30) NOT NULL,
  `tallaZapato` VARCHAR(30) NOT NULL,
  `tallaPantalon` VARCHAR(30) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `personas_idPersona` INT NOT NULL,
  `contacto_idContacto` INT NOT NULL,
  `representantes_idRepresentante` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`),
  CONSTRAINT `fk_estudiantes_personas1`
    FOREIGN KEY (`personas_idPersona`)
    REFERENCES `mydb`.`personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_contacto1`
    FOREIGN KEY (`contacto_idContacto`)
    REFERENCES `mydb`.`contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_representantes1`
    FOREIGN KEY (`representantes_idRepresentante`)
    REFERENCES `mydb`.`representantes` (`idRepresentante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_estudiantes_personas1_idx` ON `mydb`.`estudiantes` (`personas_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_estudiantes_contacto1_idx` ON `mydb`.`estudiantes` (`contacto_idContacto` ASC) VISIBLE;

CREATE INDEX `fk_estudiantes_representantes1_idx` ON `mydb`.`estudiantes` (`representantes_idRepresentante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`anioEscolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`anioEscolar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`anioEscolar` (
  `idAnio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `rango` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAnio`));


-- -----------------------------------------------------
-- Table `mydb`.`inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inscripciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inscripciones` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT,
  `calificaciones` VARCHAR(100) NOT NULL,
  `fechaInscripcion` VARCHAR(100) NOT NULL,
  `anioEscolar_idAnio` INT NOT NULL,
  `representantes_idRepresentante` INT NOT NULL,
  `estudiantes_idEstudiante` INT NOT NULL,
  PRIMARY KEY (`idInscripcion`),
  CONSTRAINT `fk_inscripciones_anioEscolar1`
    FOREIGN KEY (`anioEscolar_idAnio`)
    REFERENCES `mydb`.`anioEscolar` (`idAnio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripciones_representantes1`
    FOREIGN KEY (`representantes_idRepresentante`)
    REFERENCES `mydb`.`representantes` (`idRepresentante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripciones_estudiantes1`
    FOREIGN KEY (`estudiantes_idEstudiante`)
    REFERENCES `mydb`.`estudiantes` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_inscripciones_anioEscolar1_idx` ON `mydb`.`inscripciones` (`anioEscolar_idAnio` ASC) VISIBLE;

CREATE INDEX `fk_inscripciones_representantes1_idx` ON `mydb`.`inscripciones` (`representantes_idRepresentante` ASC) VISIBLE;

CREATE INDEX `fk_inscripciones_estudiantes1_idx` ON `mydb`.`inscripciones` (`estudiantes_idEstudiante` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `paises` (`estatus`, `codPais`, `nombrePais`) VALUES ('Activo',1,'Venezuela');

INSERT INTO `estados` (`nombreEstado`, `codEstado`, `paises_codPais`) VALUES ('Nueva Esparta',1,1);

INSERT INTO `municipios` (`nombreMunicipio`, `codMunicipio`, `estados_codEstado`) VALUES ('Municipio Antolín del Campo',1,1),('Municipio Arismendi',2,1),('Municipio Díaz',3,1),('Municipio García',4,1),('Municipio Gómez',5,1),('Municipio Maneiro',6,1),('Municipio Marcano',7,1),('Municipio Mariño',8,1),('Municipio Península de Macanao',9,1),('Municipio Tubores',10,1),('Municipio Villalba',11,1);

INSERT INTO `parroquias` (`nombreParroquia`, `codParroquia`, `municipios_codMunicipio`) VALUES ('Parroquia Antolín del Campo',1,1),('Parroquia Arismendi',2,2),('Parroquia San Juan Bautista',3,3),('Parroquia Zabala',4,3),('Parroquia García',5,4),('Parroquia Francisco Fajardo',6,4),('Parroquia Sucre',7,5),('Parroquia Matasiete',8,5),('Parroquia Bolívar',9,5),('Parroquia Aguirre',10,6),('Parroquia Maneiro',11,6),('Parroquia Juan Griego',12,7),('Parroquia Mariño',13,8),('Parroquia Boca de Río',14,9),('Parroquia San Francisco de Macanao',15,9),('Parroquia Punta de Piedras',16,10),('Parroquia Los Barales',17,10),('Parroquia San Pedro de Coche',18,11),('Parroquia Vicente Fuentes',19,11);

INSERT INTO `ciudades` (`nombreCiudad`, `codCiudad`, `parroquias_codParroquia`) VALUES ('Ciudad La Plaza de Paraguachí',1,1),('Ciudad El Cardón',2,1),('Ciudad El Salado',3,1),('Ciudad La Asunción',4,2),('Ciudad Atamo',5,2),('Ciudad Atamo Sur.',6,2),('Ciudad San Juan Bautista',7,3),('Ciudad Boquerón',8,3),('Ciudad El Macho',9,3),('Ciudad Zabala',10,4),('Ciudad El Hatico',11,4),('Ciudad El Dátil.',12,4),('Ciudad El Valle del Espíritu Santo',13,5),('Ciudad La Asuncion',14,6),('Ciudad La Sierra',15,6),('Ciudad El Maco',16,7),('Ciudad La Guardia',17,7),('Ciudad Altagracia',18,7),('Ciudad Tacarigua',19,8),('Ciudad Pedro González',20,8),('Ciudad El Cercado.',21,8),('Ciudad Santa Ana',22,9),('Ciudad El Cercado',23,9),('Ciudad El Maco',24,9),('Ciudad Los Robles',25,10),('Ciudad Maneiro',26,11),('Ciudad Pampatar',27,11),('Ciudad Juan Griego',28,12),('Ciudad Pedregales',29,12),('Ciudad Las Cabreras',30,12),('Ciudad Los Millanes',31,12),('Ciudad Porlamar',32,13),('Ciudad Bella Vista.',33,13),('Ciudad Boca de Río',34,14),('Ciudad El Junquito',35,14),('Ciudad El Maguey',36,15),('Ciudad Punta de Piedras',37,16),('Ciudad Punta Arena',38,16),('Ciudad La Blanquilla',39,16),('Ciudad El Guamache',40,17),('Ciudad Punta de Mangle',41,17),('Ciudad Los Barales',42,17),('Ciudad San Pedro de Coche',43,18),('Ciudad Las Lapas',44,18),('Ciudad El Rincón',45,18),('Ciudad Güinima',46,19),('Ciudad Guamache',47,19),('Ciudad Zulica',48,19);

