export const FIELDS_REPRESENTANTES = [
    "nombrePersona",
    "apellidoPersona",
    "cedulaPersona",
    "estadoCivil",
    "parentesco",
    "fechaNac",
    "sexoPersona",
    "telefonoPrincipal",
    "telefonoSecundario",
    "emailPrincipal",
    "emailSecundario",
    "nombreCiudad",
    "status",
];



export const FIELDS_ESTUDIANTES = [
    "idEstudiante",
    "nombrePersona",
    "apellidoPersona",
    "cedulaPersona",
    "nombreRepresentante",
    "sexoPersona",
    "nombreCiudad",
    "telefonoPrincipal",
    "telefonoSecundario",
    "emailPrincipal",
    "emailSecundario",
    "fechaNac",
    "enfermedades",
    "alergias",
    "estatura",
    "peso",
    "tallaCalzado",
    "tallaPantalon",
    "status",
];

export const FIELDS_TERRITORIOS = {
    paises: ["idPais", "nombrePais", "estatus"],
    estados: ["idEstado", "nombreEstado", "nombrePais"],
    municipios: [
        "idMunicipio",
        "nombreMunicipio",
        "nombreEstado",
        "nombrePais",
    ],
    parroquias: [
        "idParroquia",
        "nombreParroquia",
        "nombreMunicipio",
        "nombreEstado",
        "nombrePais",
    ],
    ciudades: [
        "idCiudad",
        "nombreCiudad",
        "nombreParroquia",
        "nombreMunicipio",
        "nombreEstado",
        "nombrePais",
    ],
};

export const FIELDS_MAESTROS = [
    "nombrePersona",
    "apellidoPersona",
    "cedulaPersona",
    "cargoActual",
    "estadoCivil",
    "sexoPersona",
    "fechaNac",
    "nombreCiudad",
    "telefonoPrincipal",
    "telefonoSecundario",
    "emailPrincipal",
    "emailSecundario",
];

export const FIELDS_INSCRIPCIONES = [
    "calificaciones",
    "fechaInscripcion",
    "rango",
    "nombrePersona",
    "apellidoPersona",
    "cedulaPersona",
];

export const FIELD_PRIMARY_KEY = {
    paises : "idPais",
    estados : "idEstado",
    municipios : "idMunicipio",
    parroquias : "idParroquia",
    ciudades : "idCiudad",

    maestros : "idMaestros",
    representantes : "idRepresentante",
    estudiantes : "idEstudiantes",
    inscripciones : "idInscripciones"
}

export const FIELD_HEADERS = {
    nombrePersona: "Nombre",
    apellidoPersona: "Apellido",
    cedulaPersona: "Cédula",
    estadoCivil: "Estado Civil",
    parentesco: "Parentesco",
    fechaNac: "Fecha de Nacimiento",
    sexoPersona: "Sexo",
    telefonoPrincipal: "Teléfono Principal",
    telefonoSecundario: "Teléfono Secundario",
    emailPrincipal: "Correo Principal",
    emailSecundario: "Correo Secundario",
    nombreCiudad: "Ciudad",
    status: "Estado",
    idEstudiante: "ID Estudiante",
    nombreRepresentante: "Nombre del Representante",
    enfermedades: "Enfermedades",
    alergias: "Alergias",
    estatura: "Estatura",
    peso: "Peso",
    tallaCalzado: "Talla de Calzado",
    tallaPantalon: "Talla de Pantalón",
    idPais: "ID País",
    nombrePais: "Nombre del País",
    estatus: "Estatus",
    idEstado: "ID Estado",
    nombreEstado: "Nombre del Estado",
    idMunicipio: "ID Municipio",
    nombreMunicipio: "Nombre del Municipio",
    idParroquia: "ID Parroquia",
    nombreParroquia: "Nombre de la Parroquia",
    idCiudad: "ID Ciudad",
    cargoActual: "Cargo Actual",
    calificaciones: "Calificaciones",
    fechaInscripcion: "Fecha de Inscripción",
    rango: "Rango del semestre",
};
